### ISSUE TITLE
Filteer by team in harem not working

### ISSUE THREAD

**Issue by DortenThe2nd** [zoop0kemon/hh-plus-plus#1]
When trying to use filter by team on harem screen i get this:

![image](https://user-images.githubusercontent.com/114644960/229410477-6ff1c4bc-8b38-48e1-932e-730a5c4785ce.png)

**Comment by zoop0kemon** [comment]
This should have been fixed in v1.32.12, I can't replicate the issue on the current version.

**Comment by DortenThe2nd** [comment]
Seems to be fixed, thanks
