### ISSUE TITLE
Several issues in hentaiheroes since update, errors in console

### ISSUE THREAD

**Issue by SirasB** [zoop0kemon/hh-plus-plus#16]
Hi zoop0kemon.

After the website update 27.03.24 and your script update it worked for a while, except for hiding the collected rewards in PoV, PoG. But after like 2 hours it  suddenly messed up big time. The collected rewards are now hidden properly, but some other things stopped working. The console shows errors (see below). The issues I have found so far:

- "Resource bars/Booster Tracking" Condenses the usual bars but does not display the PvP bars or the buffs; no numbers on the money. (See screenshot)
- "Fight a villain menu" does not show up
- "Home screen shortcuts" do not show up except for the club champion
- "Contest reward timer" do not show up
- "Leage" (with battle sim v4) does not show the stats for promoting/demoting any more
- "Labyrinth information" does not show the classes any more
- Hiding the links to other games doesn't work
- Event girl shard counter villains doesn't count on the villains combat screen
- Event girl shard counter PvP (Kinky cumpetition) doesn't count on the seasons combat screen
- Buff counter (e.g. Sandalwood) doesn't update during use, only at the market

Same results on web and on mobile. Did reinstall, deactivate all other scripts, clean cache.

**Screenshots**
![image](https://github.com/zoop0kemon/hh-plus-plus/assets/165282169/5407e106-38ad-4502-8b31-e7f9265b6c2e)

![image](https://github.com/zoop0kemon/hh-plus-plus/assets/165282169/32e80aaf-b97c-4c32-9e44-c751d59dd67f)

**Version info (please complete the following information):**
 - Chrome (PC), Opera GX (PC), Firefox (Android)
 - Version 1.39.15
 - Game HH
 - Platform HH.com

**Additional context**
Since there are so many new errors which worked just fine shortly before, I assume the script just crashes at some point. Console shows me several errors which do not show up when I deactivate HH++. See Screenshot.

Thank you for your great work! Love the script.

**Comment by zoop0kemon** [comment]
The script was updated for a change to the game's code bundler, but they reverted that change shortly after. For now switch back to [1.39.14](https://github.com/zoop0kemon/hh-plus-plus/raw/612c94e581cd3a0dceee4d447f2f759d0e785b57/dist/hh-plus-plus.dev.user.js), I'm working on updating the script to work with or without the bundler change.

**Comment by SirasB** [comment]
Ahh, way better again. Thank you. Couldn't find the earlier versions on my own.

**Comment by zoop0kemon** [comment]
Everything should work again now in 1.39.16
