### ISSUE TITLE
[bug]"Full in" / "Full at" timer bugged

### ISSUE THREAD

**Issue by ViperBGB** [zoop0kemon/hh-plus-plus#2]
Seems that the timer is looking to the max that we can buy and not our account max resource:
![image](https://user-images.githubusercontent.com/59071499/231573918-186446a7-406a-4ac9-92cd-22f31207e053.png)

**Comment by zoop0kemon** [comment]
This is based on a function from the game itself, so it's broken even without the script. I'm waiting to KK to fix it themselves.

**Comment by zoop0kemon** [comment]
Ok I got tired of waiting for KK to fix it and found a way to fix it myself in v1.33.1.
