### ISSUE TITLE
[bug] Double / hide Controls after update

### ISSUE THREAD

**Issue by newbykiller** [zoop0kemon/hh-plus-plus#6]
**Describe the bug**
Season/ Leages / Temple  - Indictor doubeled
first version takes to action / second takes the fill (+)-Button
Energy/Misson-Button do no longer go to the actual match/selection disabeld

**To Reproduce**
1. Go to https://www.hentaiheroes.com/
2. look on top of page 
3. Try the Buttons

**Expected behavior**

**Screenshots**
![grafik](https://github.com/zoop0kemon/hh-plus-plus/assets/139438277/4438d224-0c56-4630-84d8-1a1e5a685161)

**Version info (please complete the following information):**
 - Browser [firefox]
 - Version [115.0.2 (64-Bit)]
 - Game [ HH, GH, CxH / (global) ]
 - Platform [ HH.com, CxH.com]

**Additional context**
I'm seeing this on all games after updateing to
<html><body>

Hentai Heroes++ BDSM version | 1.36.6 |  

</body>
</html>

**Comment by zoop0kemon** [comment]
Should be fixed now in v1.36.7.
